#MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysquc-service
  labels:
    app: mysquc
  namespace: default
spec:
  ports:
  - port: 3306
  selector:
    app: mysquc
---
#MySQL PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-ucsensors
  labels:
    app: mysquc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#MySQL Container
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysquc
  labels:
    app: mysquc
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysquc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysquc
    spec:
      containers:
      - image: mysql:5.6
        name: mysquc
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Philipp1"
        ports:
        - containerPort: 3306
          name: mysquc
        volumeMounts:
        - name: mysql-persistent-storage-ucsensors
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-ucsensors
        persistentVolumeClaim:
          claimName: mysql-pv-claim-ucsensors

